services:
  mariadb:
    volumes:
      - ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.

  php:
    environment:
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      DB_DRIVER: $DB_DRIVER
      DRUSH_OPTIONS_URI: "http://${PROJECT_BASE_URL}:${PROJECT_PORT}"
      PHP_FPM_CLEAR_ENV: "no"
    volumes:
      - ./:/var/www/html
      - ./settings.docker.php:/var/www/conf/settings.docker.php #this is included via settings.php
      - ~/.cache/composer/:/home/wodby/.cache/composer/ #composer cache
      - ./docker-init/files/:/mnt/files

  crond:
    environment:
      CRONTAB: "0 * * * * drush -r ${DRUPAL_ROOT} cron"
      PHP_FPM_CLEAR_ENV: "no"
    volumes:
      - ./:/var/www/html
      - ./settings.docker.php:/var/www/conf/settings.docker.php #this is included via settings.php
      - ./docker-init/files/:/mnt/files

  nginx:
    environment:
      NGINX_SERVER_ROOT: ${DRUPAL_ROOT}
    volumes:
      - ./:/var/www/html
    labels:
      - "traefik.http.routers.${PROJECT_NAME}_nginx.rule=Host(`${PROJECT_BASE_URL}`)"
      # needed for some version of Docker Desktop.
      - "traefik.http.services.${PROJECT_NAME}_nginx.loadbalancer.server.port=80"

  # Needed if you want to use DBcode extension to connect to postgres.
  # postgres:
  #   ports:
  #   - "5432:5432"

# volumes:
#   codebase:
