version: "3"

services:
  php:
    image: wodby/drupal:$DRUPAL_TAG
    environment:
      PHP_FPM_CLEAR_ENV: "no"
    volumes:
      - codebase:/var/www/html

  nginx:
    volumes:
      - ./:/var/www/html
      - ./settings.docker.php:/var/www/html/web/sites/default/settings.local.php

volumes:
  codebase:
