version: "3.7"

services:
  php:
    # image: wodby/drupal:$DRUPAL_TAG
    environment:
      PHP_FPM_CLEAR_ENV: "no"
    volumes:
      - ./:/var/www/html
      # - ./settings.docker.php:/var/www/html/drupal/web/sites/default/settings.local.php
      - ./docker-init/files/:/mnt/files

  crond:
    # image: wodby/drupal:$DRUPAL_TAG
    environment:
      CRONTAB: "0 * * * * drush -r /var/www/html/drupal/web cron"
      PHP_FPM_CLEAR_ENV: "no"
    volumes:
      - ./:/var/www/html
      # - ./settings.docker.php:/var/www/html/drupal/web/sites/default/settings.local.php
      - ./docker-init/files/:/mnt/files

  nginx:
    ports:
      - '8000:80'
    environment:
      NGINX_SERVER_ROOT: /var/www/html/drupal/web
    volumes:
      - ./:/var/www/html

# volumes:
#   codebase:
