version: "3"

services:
  php:
    image: wodby/drupal-php:$PHP_TAG
    environment:
      PHP_FPM_CLEAR_ENV: "no"
    volumes:
      - ./:/var/www/html
      - ./settings.docker.php:/var/www/html/web/sites/default/settings.local.php
  nginx:
    ports:
      - '8000:80'
    volumes:
      - ./:/var/www/html
