version: "3"

services:
  php:
    image: wodby/drupal:$DRUPAL_TAG
    environment:
      PHP_FPM_CLEAR_ENV: "no"
    volumes:
      - ./settings.docker.php:/var/www/html/web/sites/default/settings.local.php

  nginx:
#    environment:
#      NGINX_SERVER_ROOT: /var/www/html/web
    volumes:
      - ./:/var/www/html
    ports:
      - '8000:80'
